services:
  caddy:
    container_name: caddy
    build:
      context: caddy
      dockerfile: Dockerfile
    env_file: globals.env
    volumes:
      - socket-data:/run/sockets
      - /dev/shm:/run/host_shm:rw
      - ./persist/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl/out:/etc/caddy/certs
    restart: unless-stopped
    network_mode: host

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.5
    privileged: true
    env_file: globals.env
    volumes:
      - ./persist/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    volumes:
      - ./persist/mosquitto/config:/mosquitto/config
      - ./persist/mosquitto/data:/mosquitto/data
      - ./persist/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    env_file: globals.env
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - ./persist/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB0
    ports:
      - "8080:8080"

#  djabbot:
#    container_name: djabbot
#    network_mode: host
#    image: ghcr.io/bartosz-kakol/dj_angry_birds_bot:1.0.0
#    env_file: globals.env
#    environment:
#      TOKEN: ${DJAB_TOKEN}
#      CLIENT_ID: ${DJAB_CLIENT_ID}
#    restart: always

volumes:
  socket-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=10M,mode=1777"

#networks:
#  main:
