#!/bin/bash
set -e

cd ~

if [ -z "$1" ]; then
    echo "Usage: $0 <username>" >&2
    exit 1
fi

USERNAME="$1"

PASSWORDS_FILE_PATH="data/mosquitto/config/passwords"

sudo rm -rf $PASSWORDS_FILE_PATH
docker compose run --rm mosquitto mosquitto_passwd -c /mosquitto/config/passwords $USERNAME

TARGET_UID=1883
TARGET_GID=1883

sudo chown $TARGET_UID:$TARGET_GID $PASSWORDS_FILE_PATH
sudo chmod 0600 $PASSWORDS_FILE_PATH
